import type { Site, Locale, NavMenu, MdConfig, Graduate, Prize } from "@/types";

export const SITE: Site = {
    url: "https://example.com/",
    author: "",
    describe: "北京师范大学珠海分校 ACM程序设计协会 程序设计爱好者协会 官网",
    title: "BNUZACM",
    mail: "tech@sehnsucht.top"
};

export const LOCALE: Locale = {
    lang: "zh",
    langTag: "zh-cn"
} as const;

export const MDCONFIG: MdConfig = {
    show: true,
    max: 1,
    min: 3,
}

export const NAVMENU: NavMenu[] = [
    {
        id: '1',
        name: 'ACM介绍',
        url: '/acm/',
    },
    {
        id: '2',
        name: '竞赛规则',
        url: '/rule/',
    },
    {
        id: '3',
        name: '竞赛要求',
        url: '/game/',
    },
    {
        id: '4',
        name: '校队介绍',
        url: '/team/',
    },
    {
        id: '5',
        name: '获奖情况',
        url: '/prize/',
    },
    {
        id: '6',
        name: '历届毕业',
        url: '/graduate/',
    },
    {
        id: '7',
        name: 'WeJudgeOJ',
        url: 'https://oj.bnuz.edu.cn',
    },
]

export const PRIZE: Prize[] = [
    {
        year: "2009",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "",
        players: "岑启超 刘纬经 罗衡洲",
        other: ""
    },
    {
        year: "2014",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "牛奔 冯彦钧 渠慧帆",
        other: ""
    },
    {
        year: "2009",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "李柠江 李锴 曾家东",
        other: ""
    },
    {
        year: "2019",
        game: "ACM-ICPC亚洲区域赛银川站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "GDP",
        players: "陈仰焦、曾庆望、郑景仁",
        other: ""
    },
    {
        year: "2014",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "张盛东 何俊艺 唐子惠",
        other: ""
    },
    {
        year: "2007",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "BNUEP_Blackhorse",
        players: "杨潇，杨理垚，周艳飞",
        other: ""
    },
    {
        year: "2012",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "BNUZH_Little Point",
        players: "冯彦钧 牛奔 陈源威",
        other: ""
    },
    {
        year: "2013",
        game: "ACM-ICPC中国杭州邀请赛",
        type: "ICPC",
        prize: "银奖",
        teamName: "BNUZH_RedBean",
        players: "朱嘉豪 牛奔 冯彦钧",
        other: ""
    },
    {
        year: "2015",
        game: "CCPC决赛",
        type: "CCPC",
        prize: "铜奖",
        teamName: "天使酱真的是天使！",
        players: "陈思佳，郑东吴，黎政文",
        other: ""
    },
    {
        year: "2018",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "BNUZ_Chopin In May",
        players: "叶启权、林永涛、何炜贤",
        other: ""
    },
    {
        year: "2011",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "BNUZH zhuangBility",
        players: "李锴 许翰中 王娜",
        other: ""
    },
    {
        year: "2012",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "BNUZH_SoySauce",
        players: "刘颂洋 夏玮泽 唐子惠",
        other: ""
    },
    {
        year: "2016",
        game: "ACM-ICPC亚洲区域赛CHINA-FINAL",
        type: "ICPC",
        prize: "铜奖",
        teamName: "one more time / 打完这把就学习",
        players: "郑东吴，黎政文，叶启权",
        other: ""
    },
    {
        year: "2018",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "BNUZ_Don't Move Build Orange Tree",
        players: "张经纬、黄浩荣、蒋习博",
        other: ""
    },
    {
        year: "2008",
        game: "ACM-ICPC亚洲区域赛哈尔滨站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "BNUEP_int_ijk",
        players: "杨理垚 尚鹏 许翰中",
        other: ""
    },
    {
        year: "2017",
        game: "ACM-ICPC中国广西邀请赛",
        type: "ICPC",
        prize: "铜奖",
        teamName: "I am fine",
        players: "林永涛、周琪斌、陈铿彬",
        other: ""
    },
    {
        year: "2008",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "岑启超 汪大炜 刘纬经",
        other: ""
    },
    {
        year: "2017",
        game: "ACM-ICPC中国西安邀请赛",
        type: "ICPC",
        prize: "铜奖",
        teamName: "What 7 you say?",
        players: "叶启权、叶宏杨、何炜贤",
        other: ""
    },
    {
        year: "2014",
        game: "ACM-ICPC亚洲区域赛上海站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "BNUZ_EGOist",
        players: "张盛东，何俊艺，陈思佳",
        other: ""
    },
    {
        year: "2016",
        game: "ACM-ICPC亚洲区域赛青岛站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "Beijing's friends, Are you OK?",
        players: "郑东吴，黎政文，叶启权",
        other: ""
    },
    {
        year: "2009",
        game: "ACM-ICPC亚洲区域赛上海站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "",
        players: "李锴 罗衡洲 黄伟斌",
        other: ""
    },
    {
        year: "2009",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "",
        players: "岑启超 刘纬经 罗衡洲",
        other: "",
    },
    {
        year: "2010",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "",
        players: "尚鹏 许翰中 黄伟斌",
        other: "",
    },
    {
        year: "2008",
        game: "ACM-ICPC亚洲区域赛成都站",
        type: "ICPC",
        prize: "银奖",
        teamName: "",
        players: "杨理垚 尚鹏 许翰中",
        other: "",
    },
    {
        year: "2009",
        game: "ACM-ICPC亚洲区域赛宁波站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "",
        players: "尚鹏 许翰中 曾家东",
        other: "",
    },
    {
        year: "2008",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "黄敬腾 弭家彪 安辉",
        other: "",
    },
    {
        year: "2013",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "钟文涛 崔成杰 渠慧帆",
        other: "",
    },
    {
        year: "2008",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "金奖",
        teamName: "",
        players: "杨理垚 尚鹏 杨潇",
        other: "",
    },
    {
        year: "2009",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "王倩 黄伟杰 张泽鑫",
        other: "",
    },
    {
        year: "2007",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "BNUEP_AC_Endless",
        players: "薄涛，汪大炜，岑启超",
        other: "",
    },
    {
        year: "2007",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "BNUEP_TribeHero",
        players: "周科，邹振斌，苏奕虹",
        other: "",
    },
    {
        year: "2008",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "",
        players: "魏程 许翰中 周科",
        other: "",
    },
    {
        year: "2013",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "",
        players: "朱嘉豪 牛奔 冯彦钧",
        other: "",
    },
    {
        year: "2017",
        game: "ACM-ICPC中国广西邀请赛",
        type: "ICPC",
        prize: "铜奖",
        teamName: "Don't touch us",
        players: "叶启权、张经纬、何炜贤",
        other: "",
    },
    {
        year: "2019",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "BNUZ_做啥都队",
        players: "陈建邦、袁希岚、倪士元",
        other: "",
    },
    {
        year: "2017",
        game: "ACM-ICPC亚洲区域赛西安站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "What 7 you say?",
        players: "叶启权、叶宏杨、何炜贤",
        other: "",
    },
    {
        year: "2008",
        game: "ACM-ICPC亚洲区域赛杭州站",
        type: "ICPC",
        prize: "铜奖",
        teamName: "",
        players: "岑启超 刘纬经 张泽鑫",
        other: "",
    },
    {
        year: "2011",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银奖",
        teamName: "BNUZH Clover_Z",
        players: "朱嘉豪 陈日龙 黄泽彬",
        other: "",
    },
    {
        year: "2014",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "赵天宇 朱创智 谢昌宏",
        other: "",
    },
    {
        year: "2015",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "BNUZ_天使的旋律",
        players: "蓝荣祺，方传煜，李威鹏",
        other: "",
    },
    {
        year: "2015",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "BNUZ_天使的微笑",
        players: "渠慧帆，陈思佳，邱拓先",
        other: "",
    },
    {
        year: "2011",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "",
        players: "陈继攀 刘彬彬 邵伟龙",
        other: "",
    },
    {
        year: "2017",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜奖",
        teamName: "I am fine",
        players: "周琪斌、林永涛、陈铿彬",
        other: "",
    },
    {
        year: "2009",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "金",
        teamName: "",
        players: "岑启超 刘纬经 罗衡洲",
        other: "",
    },
    {
        year: "2016",
        game: "CCPC现场赛长春站",
        type: "CCPC",
        prize: "铜",
        teamName: "切水题速度比香港记者还快",
        players: "郑东吴，黎政文，邱拓先",
        other: "",
    },
    {
        year: "2019",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "BNUZ_今年不坐滴滴",
        players: "黄浩荣、蒋习博、陈伟铎",
        other: "",
    },
    {
        year: "2013",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "",
        players: "张盛东 吴佳翎 何俊艺",
        other: "",
    },
    {
        year: "2017",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "What 7 you say?",
        players: "叶启权、叶宏杨、何炜贤",
        other: "",
    },
    {
        year: "2017",
        game: "ACM-ICPC亚洲区域赛青岛站",
        type: "ICPC",
        prize: "银",
        teamName: "please prepare your vocal",
        players: "叶启权、叶宏杨、周琪斌",
        other: "",
    },
    {
        year: "2009",
        game: "ACM-ICPC亚洲区域赛武汉站",
        type: "ICPC",
        prize: "银",
        teamName: "BNUZH_int_ijk",
        players: "尚鹏 许翰中 曾家东",
        other: "",
    },
    {
        year: "2007",
        game: "ACM-ICPC亚洲区域赛成都站",
        type: "ICPC",
        prize: "铜",
        teamName: "",
        players: "黄敬腾 汪大伟 岑启超",
        other: "",
    },
    {
        year: "2019",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银",
        teamName: "BNUZ_千层糕",
        players: "陈仰焦、曾庆望、郑景仁",
        other: "",
    },
    {
        year: "2013",
        game: "ACM-ICPC中国长沙邀请赛",
        type: "ICPC",
        prize: "铜",
        teamName: "BNUZH_EastGod",
        players: "张盛东 何俊艺 吴佳翎",
        other: "",
    },
    {
        year: "2010",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银",
        teamName: "",
        players: "曾家东 罗衡州 李柠江",
        other: "",
    },
    {
        year: "2019",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银",
        teamName: "BNUZ_[1/3] 咸鱼",
        players: "林永涛、叶启权、周琪斌",
        other: "",
    },
    {
        year: "2017",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "Get team name time out",
        players: "郑东吴、邱拓先、张经纬",
        other: "",
    },
    {
        year: "2019",
        game: "ACM-ICPC亚洲区域赛徐州站",
        type: "ICPC",
        prize: "铜",
        teamName: "forget to sign up",
        players: "陈仰焦、曾庆望、郑景仁",
        other: "",
    },
    {
        year: "2011",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "银",
        teamName: "",
        players: "王娜 许翰中 李锴",
        other: "",
    },
    {
        year: "2014",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "",
        players: "陈思佳 黄耀萩 叶超鹏",
        other: "",
    },
    {
        year: "2011",
        game: "ACM-ICPC中国福州邀请赛",
        type: "ICPC",
        prize: "铜",
        teamName: "",
        players: "朱嘉豪 陈日龙 黄泽彬",
        other: "",
    },
    {
        year: "2012",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "BNUZH_Yes_Source",
        players: "钟文涛 陆俊煜 王昌立",
        other: "",
    },
    {
        year: "2016",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "丽泽湖的蟾蜍",
        players: "郑东吴，黎政文，邱拓先",
        other: "",
    },
    {
        year: "2013",
        game: "ACM-ICPC中国长沙邀请赛",
        type: "ICPC",
        prize: "铜",
        teamName: "BNUZH_AsYouWish",
        players: "朱嘉豪 牛奔 冯彦钧",
        other: "",
    },
    {
        year: "2014",
        game: "ACM-ICPC亚洲区域赛西安站",
        type: "ICPC",
        prize: "铜",
        teamName: "BNUZ_ForgetLove",
        players: "张盛东 何俊艺 渠慧帆",
        other: "",
    },
    {
        year: "2015",
        game: "广东省大学生程序设计竞赛",
        type: "GDCPC",
        prize: "铜",
        teamName: "BNUZ_天使的绮梦",
        players: "张盛东，何俊艺，郑东吴",
        other: "",
    },
]

export const GRADUATE: Graduate[] = [
    {
        year: "2011",
        name: "唐子惠",
        to: "腾讯",
        other: "",
    },
    {
        year: "2004",
        name: "苏奕红",
        to: "金山",
        other: "",
    },
    {
        year: "2005",
        name: "杨潇",
        to: "微软",
        other: "",
    },
    {
        year: "2014",
        name: "邱拓先",
        to: "深信服",
        other: "",
    },
    {
        year: "2015",
        name: "叶启权",
        to: "字节跳动",
        other: "",
    },
    {
        year: "2003",
        name: "李邦辉",
        to: "工行软件",
        other: "",
    },
    {
        year: "2003",
        name: "何侃辉",
        to: "汇丰银行",
        other: "",
    },
    {
        year: "2010",
        name: "牛奔",
        to: "360",
        other: "",
    },
    {
        year: "2002",
        name: "王倩",
        to: "中金",
        other: "",
    },
    {
        year: "2014",
        name: "郑东吴",
        to: "金山",
        other: "",
    },
    {
        year: "2009",
        name: "刘晓佳",
        to: "北京邮电大学->中国电信",
        other: "",
    },
    {
        year: "2015",
        name: "叶宏杨",
        to: "东方海外",
        other: "",
    },
    {
        year: "2015",
        name: "周琪斌",
        to: "北京师范大学",
        other: "",
    },
    {
        year: "2009",
        name: "马天游",
        to: "腾讯",
        other: "",
    },
    {
        year: "2012",
        name: "吴佳翎",
        to: "美图",
        other: "",
    },
    {
        year: "2012",
        name: "程鑫",
        to: "东方海外",
        other: "",
    },
    {
        year: "2002",
        name: "周志明",
        to: "远光",
        other: "",
    },
    {
        year: "2006",
        name: "刘伟经",
        to: "facebook",
        other: "",
    },
    {
        year: "2003",
        name: "王泽辉",
        to: "创业",
        other: "",
    },
    {
        year: "2003",
        name: "江嘉源",
        to: "江西景德镇人民银行",
        other: "",
    },
    {
        year: "2007",
        name: "李锴",
        to: "兴业银行",
        other: "",
    },
    {
        year: "2010",
        name: "刘颂洋",
        to: "香港daolab",
        other: "",
    },
    {
        year: "2013",
        name: "陈思佳",
        to: "德克萨斯大学达拉斯分校",
        other: "",
    },
    {
        year: "2012",
        name: "渠慧帆",
        to: "北京邮电大学 airbnb",
        other: "",
    },
    {
        year: "2002",
        name: "周光进",
        to: "东方海外",
        other: "",
    },
    {
        year: "2010",
        name: "陈源威",
        to: "腾讯",
        other: "",
    },
    {
        year: "2016",
        name: "林永涛",
        to: "字节跳动",
        other: "",
    },
    {
        year: "2003",
        name: "安辉",
        to: "公安网监",
        other: "",
    },
    {
        year: "2003",
        name: "艾森哲",
        to: "创业",
        other: "",
    },
    {
        year: "2005",
        name: "汪大炜",
        to: "金山",
        other: "",
    },
    {
        year: "2006",
        name: "尚鹏",
        to: "金山",
        other: "",
    },
    {
        year: "2007",
        name: "许翰中",
        to: "Oregon State University",
        other: "",
    },
    {
        year: "2004",
        name: "黄敬腾",
        to: "华为",
        other: "",
    },
    {
        year: "2016",
        name: "张经纬",
        to: "西山居",
        other: "",
    },
    {
        year: "2003",
        name: "黄静腾",
        to: "华为",
        other: "",
    },
    {
        year: "2003",
        name: "倪家标",
        to: "中海油",
        other: "",
    },
    {
        year: "2004",
        name: "黄伟杰",
        to: "金山",
        other: "",
    },
    {
        year: "2005",
        name: "岑启超",
        to: "猎豹",
        other: "",
    },
    {
        year: "2003",
        name: "彭锐",
        to: "华为",
        other: "",
    },
    {
        year: "2010",
        name: "钟文清",
        to: "腾讯",
        other: "",
    },
    {
        year: "2005",
        name: "熊立勇",
        to: "金山",
        other: "",
    },
]